# Generated by Django 2.0.2 on 2020-04-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depDate', models.DateField()),
                ('depTime', models.TimeField()),
                ('depZip', models.IntegerField()),
                ('arrZip', models.IntegerField()),
                ('driEmail', models.EmailField(max_length=254)),
            ],
        ),
    ]
