# Generated by Django 3.0.4 on 2020-04-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rides',
            name='reserved',
            field=models.TextField(default='Open'),
        ),
    ]
