# Generated by Django 3.0.4 on 2020-04-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0003_auto_20200421_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='driSmokes',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='rides',
            name='riderLugg',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rides',
            name='riderPets',
            field=models.BooleanField(),
        ),
    ]
