# Generated by Django 3.0.4 on 2020-04-21 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0005_auto_20200421_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='driSmokes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rides',
            name='riderPets',
            field=models.IntegerField(default=0),
        ),
    ]
