# Generated by Django 3.0.4 on 2020-04-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0006_auto_20200421_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='rides',
            name='seatCapacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rides',
            name='seatTaken',
            field=models.IntegerField(default=0),
        ),
    ]
