# Generated by Django 3.0.5 on 2020-05-06 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0007_auto_20200427_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='rides',
            name='riderPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
