# Generated by Django 3.0.5 on 2020-05-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0008_rides_riderprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='riderPrice',
            field=models.IntegerField(default=0),
        ),
    ]
