# Generated by Django 3.0.5 on 2020-05-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0009_auto_20200505_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='arrZip',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rides',
            name='depZip',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rides',
            name='riderPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
